# John Doe Jekyll Theme Config

title: Βιργίλιος Στάρκγουελ
email: vstarkwell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  μικρές ιστορίες
baseurl: "/journal" # the subpath of your site, e.g. /blog
url: "https://vstarkwell.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
host:

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
